Added new headers for cache control to cameras snap endpoints
prusa3d/Prusa-Link pull request #562
Opened 2022-11-07 13:20 UTC by Majkluss

2022-11-08 11:49 UTC, Majkluss commented on prusa/link/web/cameras.py
> +        'Expires': str(last_modified + timedelta(seconds=10)),
const

2022-11-08 11:49 UTC, Majkluss commented on prusa/link/web/cameras.py
> +        'Cache-Control': 'private, max-age=604800'
expire

2022-11-08 11:51 UTC, Majkluss commented on prusa/link/web/cameras.py
> +HEADER_DATETIME_FORMAT = "%a, %d %b %Y %X GMT"
This value is used in more places, move it to the const

2022-11-15 09:33 UTC, ondratu requested changes

2022-11-15 09:33 UTC, ondratu commented on prusa/link/web/cameras.py
> +        'Date': last_modified_str,
I think, that `Date` header should be datetime of response....
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date

2022-11-15 10:37 UTC, ondratu approved these changes

2022-11-15 10:37 UTC, merged