Fixed update command
prusa3d/Prusa-Link pull request #666
Opened 2023-02-22 15:52 UTC by Majkluss

2023-02-22 16:38 UTC, ondratu requested changes

2023-02-22 16:38 UTC, ondratu commented on prusa/link/web/main.py
> +        print("Update!")
WTF print?!

2023-02-23 07:36 UTC, Majkluss commented on prusa/link/web/main.py
> +        print("Update!")
Sorry, my bad from the debugging :)

2023-02-23 08:47 UTC, ondratu approved these changes

2023-02-23 08:47 UTC, merged