Add a setting that allows the user to disable the error beeps
prusa3d/Prusa-Link pull request #705
Opened 2023-03-21 19:02 UTC by TojikCZ

2023-03-22 15:40 UTC, ondratu requested changes

2023-03-22 15:40 UTC, ondratu commented on prusa/link/config.py
> +                    ("error_chime", bool, True),
Move that to printer_settings_ini:
```
[printer]
error_chime=True
```

2023-03-27 18:29 UTC, TojikCZ commented on prusa/link/config.py
> +                    ("error_chime", bool, True),
Is this okay?

2023-03-28 07:16 UTC, ondratu approved these changes

2023-03-28 07:16 UTC, merged