Refactor multi-instance, add web proxy
prusa3d/Prusa-Link pull request #768
Opened 2023-05-26 16:47 UTC by TojikCZ

2023-06-05 10:04 UTC, ondratu requested changes

2023-06-05 13:49 UTC, TojikCZ commented on prusa/link/multi_instance/config_component.py
> +        self.refresh_udev_rules()
Sorry, but I find this response rather unhelpful. What is the problem you see that I don't?

2023-06-05 13:51 UTC, TojikCZ commented on prusa/link/multi_instance/__main__.py
> +                print(f"{name} not running, but PID file locked. "
Because print gets written out to the terminal while logging is being routed to the system log

2023-06-05 13:57 UTC, TojikCZ commented on prusa/link/multi_instance/config_component.py
> +            os.chown(data_folder, self.user_info.pw_uid,
yes I know, I added it in the same commit as this line. A simple "You forgot about this use case" Would have sufficed, no need for the snark.

2023-06-05 15:40 UTC, TojikCZ commented on prusa/link/multi_instance/__main__.py
> +        Thread(target=inner, name="mi_stopper", daemon=False).start()
Yea, the first time around the main thread was the one that ran the web server or read from the pipe, that's not how it is right now, so yes, I can get by without stop threads. Weird stuff will start happening if anyone touches stopping or the main thread in the future tho

2023-06-05 18:43 UTC, TojikCZ commented on prusa/link/multi_instance/config_component.py
> +        self.refresh_udev_rules()
Is this for the WTF/minute statistic?

2023-06-07 09:33 UTC, ondratu approved these changes

2023-06-07 09:33 UTC, merged